export default {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SET_TOKEN: 'SET_TOKEN',
  SET_USER: 'SET_USER',
  SET_LOCALE: 'SET_LOCALE',
  TOGGLE_LOCALE: 'TOGGLE_LOCALE',
  TOGGLE_THEME: 'TOGGLE_THEME',
  FIRST_START: 'FIRST_START'
}
